# Generated by Django 5.2.2 on 2026-05-06 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_models', '0002_alter_songuser_played_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songuser',
            name='correct_guesses',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='songuser',
            name='wrong_guesses',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
